const LOADING = 'LOADING';
const ADD_POSTS = 'ADD_POSTS';
const REMOVE_POSTS = 'REMOVE_POSTS';
const UPDATE_POSTS = 'UPDATE_POSTS';
const FETCH_COMMENTS = 'FETCH_COMMENTS';
const SET_FILTER = 'SET_FILTER';
const ERROR = 'ERROR';

export {
  LOADING,
  ADD_POSTS,
  REMOVE_POSTS,
  UPDATE_POSTS,
  FETCH_COMMENTS,
  SET_FILTER,
  ERROR,
};
