const LOADING = 'LOADING';
const ADD_POSTS = 'ADD_POSTS';
const REMOVE_POSTS = 'REMOVE_POSTS';
const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_COMMENTS = 'FETCH_COMMENTS';
const ERROR = 'ERROR';

export {
    LOADING,
    ADD_POSTS,
    REMOVE_POSTS,
    FETCH_POSTS,
    FETCH_COMMENTS,
    ERROR
};
