const LOADING = 'LOADING';
const ADD_POSTS = 'ADD_POSTS';
const REMOVE_POSTS = 'REMOVE_POSTS';
const UPDATE_POSTS = 'UPDATE_POSTS';
const FETCH_COMMENTS = 'FETCH_COMMENTS';
const SET_FILTER = 'SET_FILTER';
const ERROR = 'ERROR';
const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export {
  LOADING,
  ADD_POSTS,
  REMOVE_POSTS,
  UPDATE_POSTS,
  FETCH_COMMENTS,
  SET_FILTER,
  ERROR,
  OPEN_SNACKBAR,
  CLOSE_SNACKBAR,
};
